### ISSUE TITLE
这个地址我访问报 502

### ISSUE THREAD

**Issue by shanxiaoyan2022** [shuise/web-developer-guide#2]
http://nodejs.cn/learn/an-introduction-to-the-npm-package-manager
这个地址我访问报 502
https://www.w3schools.com/whatis/whatis_npm.asp
我觉得这个写的还蛮清楚的。

**Comment by shuise** [comment]
我这儿访问可以，不管代理与否，你切换代理或者网络试试

**Comment by shanxiaoyan2022** [comment]
的确可以，正常可访问了。
